datasets:
  ilsvrc2012:
    name: &dataset_name 'cifar10'
    type: 'CIFAR10'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &cifar10_train !join [*dataset_name, '/train']
        params:
          train: True
          download: True
          root: *root_dir
          transform_params:
            - &randomhorizontalflip
              type: 'RandomHorizontalFlip'
            - &totensor
              type: 'ToTensor'
            - &normalize
              type: 'Normalize'
              params: 
                mean: [0.4914, 0.4822, 0.4465]
                std: [0.2023, 0.1994, 0.2010]
            
      val:
        dataset_id: &cifar10_val !join [*dataset_name, '/val']
        params:
          download: True
          train: False
          root: *root_dir
          transform_params:
            - *totensor
            - *normalize

models:
  teacher_model:
    name: 'LeNetDrop'
    classification_model:
      name: &teacher_model_name 'LeNetDrop'
      params:
        num_classes: 10
        pretrained: False
      experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['/home/bepi/Desktop/Ph.D_/projects/dropout_rel_assessment/models', *teacher_experiment, '.pth']
    params:
      num_classes: 10
  
test:
  test_data_loader:
    dataset_id: *cifar10_val
    random_sample: False
    batch_size: 1
    num_workers: 16
